### ISSUE TITLE
bug: Cannot add colour to CoreH5

### ISSUE THREAD

**Issue by Swrnv-qc** [wrappid/guide-module#14]
## Description

I am encountering an issue when attempting to apply color to `<CoreH5>` using styleClasses, as no visible style changes occur.

### Expected behavior:
Adding `styleClasses={[CoreClasses.COLOR.TEXT_SUCCESS_DARK]}` to `<CoreH5>` should modify the font color accordingly.

I am utilizing the `TEXT_SUCCESS_DARK` style class from "/guide/styles," but it doesn't seem to be taking effect. I have encountered the bug specifically in web mode.

**Comment by irkfaisal** [comment]
Text color is currently not working, issue also mentioned in style documentation.

**Comment by Edithmark42** [comment]
The issue regarding CoreH and CoreTypography not adding color is fixed in the Styles  #package.
for further information please refer to the issue : #https://github.com/wrappid/styles/issues/9
