### ISSUE TITLE
Components of data display verification

### ISSUE THREAD

**Issue by arkaprota** [wrappid/guide-module#149]
## Description

checking description and reviewing it: 

1. weather the components are displaying or not 
2.  description are given or not
3. code is showing or not
4. color that are present are ok
5.  other type of bugs

**Comment by techoneel** [comment]
@arkaprota please update with the latest status of the issue.
@anantakumarghosh please close the issue if it's done.

**Comment by anantakumarghosh** [comment]
Closing as done.
