### ISSUE TITLE
TOC Implementation

### ISSUE THREAD

**Issue by Edithmark42** [wrappid/guide-module#16]
- [x] https://github.com/wrappid/guide-module/issues/29#issuecomment-1898306837
- [x] https://github.com/wrappid/guide-module/issues/38#issue-2072251886
- [x] https://github.com/wrappid/guide-module/issues/27#issue-2071896695
- [x] https://github.com/wrappid/guide-module/issues/27#issuecomment-1890350279
- [x] https://github.com/wrappid/guide-module/issues/26#issue-2071874204
- [x] https://github.com/wrappid/guide-module/issues/26#issuecomment-1886382108
- [x] https://github.com/wrappid/guide-module/issues/26#issuecomment-1891931832
- [x] https://github.com/wrappid/guide-module/issues/20#issue-2071692872
- [x] https://github.com/wrappid/guide-module/issues/20#issuecomment-1886351699
- [ ] https://github.com/wrappid/guide-module/issues/20#issuecomment-1895648457

**Comment by jyoti1610** [comment]
- [ ] https://github.com/wrappid/guide-module/issues/29#issuecomment-1898306837
- [ ] https://github.com/wrappid/guide-module/issues/38#issue-2072251886
- [ ] https://github.com/wrappid/guide-module/issues/27#issue-2071896695
- [ ] https://github.com/wrappid/guide-module/issues/27#issuecomment-1890350279
- [ ] https://github.com/wrappid/guide-module/issues/26#issue-2071874204
- [ ] https://github.com/wrappid/guide-module/issues/26#issuecomment-1886382108
- [ ] https://github.com/wrappid/guide-module/issues/26#issuecomment-1891931832
- [ ] https://github.com/wrappid/guide-module/issues/20#issue-2071692872
- [ ] https://github.com/wrappid/guide-module/issues/20#issuecomment-1886351699
- [ ] https://github.com/wrappid/guide-module/issues/20#issuecomment-1895648457

**Comment by Edithmark42** [comment]
@Animesh1432 please refer to the [MUI ](https://mui.com/material-ui/migration/troubleshooting/) page for the consecutive scrollbar .

**Comment by Edithmark42** [comment]
#38  the issue is dependent upon #37 so here I'm marking it.

**Comment by Edithmark42** [comment]
#26 please re-check this issue and inform, if any changes are required!

**Comment by samhere17** [comment]
Related Issues:

wrappid/guide-module#11
wrappid/guide-module#12
wrappid/guide-module#16
wrappid/core#65
wrappid/core#69

**Comment by Animesh1432** [comment]
As of now closing this issue
