### ISSUE TITLE
  Write script  for move file based on core components folder structure

### ISSUE THREAD

**Issue by PritamIT2023** [wrappid/guide-module#2]
Write nodejs script for move file  same as core directory in guide-module docs folder

**Comment by PritamIT2023** [comment]
This issue should be closed.

**Comment by samhere17** [comment]
@PritamIT2023 when you say this should be closed, do you mean the work was done?
If work was done, where are the source code?
Kindly check-in your script files in a folder named "dev".

We can close the issue after that.

**Comment by PritamIT2023** [comment]
@samhere17 
Please check. I have checked in the necessary files.

**Comment by samhere17** [comment]
Files are now available.
