### ISSUE TITLE
Style Utilities: Alignment problem in TOC 

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#20]
In TOC Alignment should be changed.

**Comment by Edithmark42** [comment]
More information required with screenshots. Do not understand what changes needs to be done.

**Comment by Animesh1432** [comment]
In right side " Table of content" the content's alignment is not right.

![Image](https://github.com/wrappid/guide-module/assets/105671990/6ac64145-4caa-426e-9462-346a79f7beb7)

you can see here "Table of content" is in left alignment nut other words like "Dv_border","border","BG","Color" this words are in central alignment. It will looks good if all the things will be in left alignment like reference document.

look how they align the content beautifully 
![Image](https://github.com/wrappid/guide-module/assets/105671990/405df333-1708-4267-a08b-edabebbe3319)

One more additional suggestion is try to add some icons for each utilities it looks more attractive.

**Comment by Animesh1432** [comment]
1.![image](https://github.com/wrappid/guide-module/assets/105671990/ef23605d-3947-4351-848f-82b5a1d17b8a)
 Not in alphabetic order.
2.
![image](https://github.com/wrappid/guide-module/assets/105671990/87f1ae12-aff2-4347-a827-05dfa1f868fb)
 why this red line is here ??

**Comment by jyoti1610** [comment]
Duplicate issue exsit in #16 
**Issue status :** Transfered to issue no. #16 
**App Info :**

|  Key  |  Value  |
| ---- | ---- |
| Fronend URL | http://wrappid.framework.s3-website.ap-south-1.amazonaws.com/guide/styles |
| Fronend Version | 0.0.5 |

**Desktop :**

|  Key  |  Value  |
| ---- | ---- |
| OS | Wisdows 11 |
| Browser | Google Chrome |
| Version | 120.0.6099.225 (Official Build) (64-bit) |
