### ISSUE TITLE
Style utilities : Page scrolling problem due to VW_100

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#21]
The page should not scrolled right to left but it can be scrolled right to left.

**Comment by Edithmark42** [comment]
This problem is arising due to the View Width 100 or VW_100 value. We are actively working on it.
For the time being we have removed the width from the documentation page.

**Comment by jyoti1610** [comment]
Fix the problem which is arising due to VW_100 value as soon as possible.

**Comment by Edithmark42** [comment]
Please close this issue as it is dependent on a related issue Ref #37 
@Animesh1432 @jyoti1610

**Comment by Animesh1432** [comment]
As of now closing this issue
