### ISSUE TITLE
Style utilities : proper heading and description missing

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#22]

**Comment by Edithmark42** [comment]
Please provide some information about the exact problems and kindly attach some screenshot about the same.

**Comment by Animesh1432** [comment]
It is all about how it looks good and informative.

When you are making any guide then you should write some instruction. you just copy some of content from reference document but there is no any instruction or any description about the utilities.

Just see how reference document did it 


![Image](https://github.com/wrappid/guide-module/assets/105671990/40bffd76-82ba-45ed-95d6-53bcfda1ad64)

they just add a proper description. And this description looking absolutely perfect this is not looking unnecessary they use some highlights to attract human eye. Just compare your guide and reference doc which one is looking nice and which looks like actual guide.

Use some description instruction to looks it like a proper guide

**Comment by Animesh1432** [comment]
And why you use yellow color for every box ? is it your specific instruction or theme? or you are following theme? @Edithmark42

**Comment by Edithmark42** [comment]
For theme and color specific details kindly refer to the current theme palette configuration which is mentioned in the issue : [DEV_BORDER](https://github.com/wrappid/guide-module/issues/25#issuecomment-1891345008).

**Comment by Animesh1432** [comment]
that comment is not sufficient to test.
cannot find the reason why you use yellow color.

**Comment by Animesh1432** [comment]
> It is all about how it looks good and informative.
> 
> When you are making any guide then you should write some instruction. you just copy some of content from reference document but there is no any instruction or any description about the utilities.
> 
> Just see how reference document did it
> 
> ![Image](https://private-user-images.githubusercontent.com/105671990/295807858-40bffd76-82ba-45ed-95d6-53bcfda1ad64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTQxMDQsIm5iZiI6MTcwNTQ5MzgwNCwicGF0aCI6Ii8xMDU2NzE5OTAvMjk1ODA3ODU4LTQwYmZmZDc2LTgyYmEtNDVlZC05NWQ2LTUzYmNmZGExYWQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxMjE2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzgyNGU5MzliZTFiYjAxODEzOWFhMzlmYjRiMjJiN2U5OThmMmNkYzY3Y2JmZjRlMDg2ODI3ZDBlMDUyZDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kypdK0RabExbyuw_D0XIx_A3f9sxjCb8AvWRrcTsSbE)
> 
> they just add a proper description. And this description looking absolutely perfect this is not looking unnecessary they use some highlights to attract human eye. Just compare your guide and reference doc which one is looking nice and which looks like actual guide.
> 
> Use some description instructions to looks it like a proper guide

What about this ????

**Comment by Edithmark42** [comment]
Please check if further changes are required!

**Comment by Animesh1432** [comment]
As of now closing this issue
