### ISSUE TITLE
Style Utilities : Spacing Problem 

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#24]
In the document Spacing between two points should be the same. In the guide space between "Style Utilities" and "DEV_BORDER" is not the same comparing the space between "DEV_BORDER" and "BG".

**Comment by Edithmark42** [comment]
Please provide some specific details, with screenshots.

**Comment by Animesh1432** [comment]
![image](https://github.com/wrappid/guide-module/assets/105671990/93b42892-167a-43e2-a25c-704a67a827e0)
Highlighted the gap between 2 sections this gap should be the same.

**Comment by Animesh1432** [comment]
As of now closing this issue
