### ISSUE TITLE
Style Utilities : Dev-Border

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#25]
1. How can I know that the border you are suggesting is right?
 2. if the border renders in different colors in different screen sizes then there should be mentioned the size for every color.
 3.  you created a red-colored box where you put a tiny border in the middle. size should be specific it does not look good.
 4. Here you use a button for expanding code. Did you use this button for every section? if not, why?
 5. Why did you use pink color for the code section? which you are using?

**Comment by Edithmark42** [comment]
1. The DEV_BORDER is used for development and testing/debugging purposes. So it must be which looks different from the other borders. 
![dev](https://github.com/wrappid/guide-module/assets/58048663/e5daf789-1417-416c-a7cb-36ffa257d10f)

2. The border will be automatically applied to all the divisions and elements when the app is opened in the development mode.
3. Its target is not to look good rather to look different. so that elements in a page could be distinguished easily.

**Comment by Edithmark42** [comment]
4. We are going add the code block to all the utilities. 
5. The color of the elements is subjected to theme specific styling. So, it will change based on the predefined theme color.

**Comment by Animesh1432** [comment]
provide me theme doc for testing 
5. pending

**Comment by Edithmark42** [comment]
The theme palette used for this documentation page at the time of this comment is as follows:

> "common": {
>             "black": "#000",
>             "white": "#fff"
>         },
>         "type": "light",
>         "primary": {
>             "light": "#92f0a0",
>             "main": "#27d640",
>             "dark": "#038516",
>             "contrastText": "#fff"
>         },
>         "secondary": {
>             "light": "#FAFAFA",
>             "main": "#f50057",
>             "dark": "#FAFAFA",
>             "contrastText": "#fff"
>         },
>         "error": {
>             "light": "#e57373",
>             "main": "purple",
>             "dark": "#d32f2f",
>             "contrastText": "#fff"
>         },
>         "warning": {
>             "main": "#ff9800",
>             "light": "#ffb74d",
>             "dark": "#f57c00",
>             "contrastText": "rgba(0, 0, 0, 0.87)"
>         },
>         "info": {
>             "main": "#2196f3",
>             "light": "#64b5f6",
>             "dark": "#1976d2",
>             "contrastText": "#fff"
>         },
>         "success": {
>             "main": "red",
>             "light": "#81c784",
>             "dark": "#388e3c",
>             "contrastText": "rgba(0, 0, 0, 0.87)"
>         },
>         "grey": {
>             "50": "#fafafa",
>             "100": "#f5f5f5",
>             "200": "#eeeeee",
>             "300": "#e0e0e0",
>             "400": "#bdbdbd",
>             "500": "#9e9e9e",
>             "600": "#757575",
>             "700": "#616161",
>             "800": "#424242",
>             "900": "#212121",
>             "A100": "#d5d5d5",
>             "A200": "#aaaaaa",
>             "A400": "#303030",
>             "A700": "#616161"
>         },
>         "contrastThreshold": 3,
>         "tonalOffset": 0.2,
>         "text": {
>             "primary": "rgba(0, 0, 0, 0.87)",
>             "secondary": "rgba(0, 0, 0, 0.54)",
>             "disabled": "rgba(0, 0, 0, 0.38)",
>             "hint": "rgba(0, 0, 0, 0.38)"
>         },
>         "divider": "rgba(0, 0, 0, 0.12)",
>         "background": {
>             "paper": "#fff",
>             "default": "#fafafa"
>         },
>         "action": {
>             "active": "rgba(0, 0, 0, 0.54)",
>             "hover": "rgba(0, 0, 0, 0.08)",
>             "hoverOpacity": 0.08,
>             "selected": "rgba(0, 0, 0, 0.14)",
>             "disabled": "rgba(0, 0, 0, 0.26)",
>             "disabledBackground": "rgba(0, 0, 0, 0.12)"
>         }

**Comment by Animesh1432** [comment]
As of now closing this issue
