### ISSUE TITLE
Style Utilities : Two consecutive scroll bar TOC and  body

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#26]
![image](https://github.com/wrappid/guide-module/assets/105671990/91e2f98e-81c2-42ea-92b1-43e340f524c7)

**Comment by Animesh1432** [comment]
![image](https://github.com/wrappid/guide-module/assets/105671990/949d9bd0-f070-4be3-9e44-70202353103f)
 why there is these much black space I highlighted the space with a yellow color

**Comment by Animesh1432** [comment]
Now it is working but something seems not right

- 
![image](https://github.com/wrappid/guide-module/assets/105671990/c9e2c8d2-5657-4ddc-a68a-541e6992fb8f)
when we scroll the main page and TOC both navigation scroll bars are in the same place that is not looking right you can main sections scroll bar beside the division line

**Comment by jyoti1610** [comment]
Duplicate issue exsit in #16 
**Issue status :** Transfered to issue no. #16 
**App Info :**

|  Key  |  Value  |
| ---- | ---- |
| Fronend URL | http://wrappid.framework.s3-website.ap-south-1.amazonaws.com/guide/styles |
| Fronend Version | 0.0.5 |

**Desktop :**

|  Key  |  Value  |
| ---- | ---- |
| OS | Wisdows 11 |
| Browser | Google Chrome |
| Version | 120.0.6099.225 (Official Build) (64-bit) |
