### ISSUE TITLE
Style Utilities : Space for TOC

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#27]
![image](https://github.com/wrappid/guide-module/assets/105671990/42f21ece-3d40-4980-8dc0-d2c2beae204c)
 There should be more space between the utility section and TOC

**Comment by Animesh1432** [comment]
1. Missing Header
![image](https://github.com/wrappid/guide-module/assets/105671990/f387d492-5e9e-474c-8203-5984fb1df05d)
2. Extra space above the TOC and some part of the red division line is missing
3. 
![image](https://github.com/wrappid/guide-module/assets/105671990/e1af057c-2490-4e89-be6b-f11b6fd35aad)

**Comment by jyoti1610** [comment]
Duplicate issue exsit in #16 
**Current status of the issue :** Transfered to issue no. #16 
**App Info :**

|  Key  |  Value  |
| ---- | ---- |
| Fronend URL | http://wrappid.framework.s3-website.ap-south-1.amazonaws.com/ |
| Fronend Version | 0.0.5|

**Desktop :**

|  Key  |  Value  |
| ---- | ---- |
| OS | Windows 11 |
| Browser | Google Chrome |
| Version | 120.0.6099.225 (Official Build) (64-bit) |
