### ISSUE TITLE
Style Utilities : BG

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#28]
1. what is BG? Use proper heading.
2. "so in some cases you’ll want to use CoreClasses.COLOR.TEXT_<contextual-class>"
 suggestion - "so in some cases you’ll have to use CoreClasses.COLOR.TEXT_<contextual-class>".
3.  how can I know you used appropriate colors? Provide The document you use for colors.

**Comment by Animesh1432** [comment]
1. Test Fail
![image](https://github.com/wrappid/guide-module/assets/105671990/0b23fa30-1bbb-451d-a07e-483ac677a01a)
2. Test fail
![image](https://github.com/wrappid/guide-module/assets/105671990/3fb11930-e475-4348-a3b4-a38d61b0a6b9)
3. share me wrappid theme

**Comment by Animesh1432** [comment]
1. make font color white 
![image](https://github.com/wrappid/guide-module/assets/105671990/e4501cb4-b0e6-4682-82b5-191f7be5ffb8)
2.
![image](https://github.com/wrappid/guide-module/assets/105671990/3bbc7812-3fae-4a54-81e4-bef9f131313b)
fix this

**Comment by Edithmark42** [comment]
The issues related to the background color are resolved as of now. kindly check the changes in the next release!

**Comment by Animesh1432** [comment]
As of now closing this issue
