### ISSUE TITLE
Style Utilities : Incomplete TOC

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#29]
![image](https://github.com/wrappid/guide-module/assets/105671990/5d891926-3950-4586-a47c-6430feac7ac3)

**Comment by Edithmark42** [comment]
Could not provide custom height as of now so it is on Hold.

**Comment by jyoti1610** [comment]
**Problem :**
![Screenshot 2024-01-18 165436](https://github.com/wrappid/guide-module/assets/88906858/216e539a-ca11-4aca-8025-ba6d47f17eb4)

Fill this blank space .

**Comment by jyoti1610** [comment]
Duplicate issue exsit in #16 
**Issue status :** Transfered to issue no. #16 
**App Info :**

|  Key  |  Value  |
| ---- | ---- |
| Fronend URL | http://wrappid.framework.s3-website.ap-south-1.amazonaws.com/guide/styles |
| Fronend Version | 0.0.5 |

**Desktop :**

|  Key  |  Value  |
| ---- | ---- |
| OS | Wisdows |
| Browser | Google Chrome |
| Version | 120.0.6099.225 (Official Build) (64-bit) |
