### ISSUE TITLE
Style Utilities : Color

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#31]
Share necessary Document for testing

**Comment by Edithmark42** [comment]
@Animesh1432  You can go through the [Bootstrap 5](https://getbootstrap.com/docs/4.0/utilities/colors/) documentation for reference. As I can see the Text color is working as required.

**Comment by Edithmark42** [comment]
For reference I'm attaching the current color palette.
![color palette](https://github.com/wrappid/guide-module/assets/58048663/258ac10b-565c-40c8-9dcd-a282e77296df)

**Comment by Animesh1432** [comment]
How can I test the color section when you are giving me the testing section as a reference document?
A theme document should be there with a proper details.

**Comment by Edithmark42** [comment]
color palette will be provided soon.

**Comment by Animesh1432** [comment]
As of now closing this issue
