### ISSUE TITLE
Style Utilities : TEXT issues

### ISSUE THREAD

**Issue by jyoti1610** [wrappid/guide-module#32]
1. Provide me the proper documentaion as I can check the information which you have written  in the TEXT div. As example ' BOLD=700 '    (How I came to know that it's an accurate information ?).
2. It's my suggestion that first letter of every  second word of every heading should in upper case, as example ( Text alignment to Text Alignment ). I think it looks more  appropiate to the user.
3. In " Text decoration " the boxes sequence and huge gap in bottom right might looks odd to the user.   
4. Most importantly the boxes of sample text should keep in exactly under the particular heading.
5.  It's a sugggestion before every sample text need a colon instead of fullstop, which looks better. As example ( "TEXT_WEIGHT_SEMIBOLD sample. Fusce mattis egestas risus, in euismod odio tincidunt in" to "TEXT_WEIGHT_SEMIBOLD sample : Fusce mattis egestas risus, in euismod odio tincidunt in." ).
6. The type of text which are mentioned here like TEXT_WEIGHT_LIGHTER ,TEXT_WEIGHT_LIGHT seems same to the user.
7. The type of text which are mentioned here like TEXT_WEIGHT_NORMAL ,TEXT_WEIGHT_MEDIUM seems same to the user.
8. The type of text which are mentioned here like TEXT_WEIGHT_SEMIBOLD ,TEXT_WEIGHT_BOLD ,TEXT_WEIGHT_BOLDER seems same to the user.

**Comment by Edithmark42** [comment]
1. for specific details please follow the bootstrap documentation.
3.  It will be there because we need to show that Text truncate is working so it will basically truncate more than one lines.
5. that was just a demo text for demonstration purpose. 
for comment index 6. , 7. ,8. : Those are working as expected. Please refer to the font weight documentation.

**Comment by jyoti1610** [comment]
1.  I am checking for this.
2.  **Possible Solution :** 
     
![image](https://github.com/wrappid/guide-module/assets/88906858/21ef2c7b-1f6a-4764-8069-31b1fc34410c)

It's a suggestion if possible use such type of boxes over there .

5. This is passed.

**NB :** Rest are try to solve as soon as possible.

**Comment by Animesh1432** [comment]
As of now closing this issue
