### ISSUE TITLE
Style Utilities : OVERFLOW not working

### ISSUE THREAD

**Issue by jyoti1610** [wrappid/guide-module#34]
1.In overflow section OVERFLOW_AUTO is not working as per information provided.
2. In overflow section OVERFLOW_HIDDEN is not working as per information provided.
3. In overflow section OVERFLOW_VISIBLE is not working as per information provided.
4. In overflow section OVERFLOW_SCROLL is not working as per information provided.
5. In overflow section OVERFLOW_X_AUTO is not working as per information provided.
6. In overflow section OVERFLOW_X_HIDDEN is not working as per information provided.
7. In overflow section OVERFLOW_X_VISIBLE is not working as per information provided.
8. In overflow section OVERFLOW_X_SCROLL is not working as per information provided.
9. In overflow section OVERFLOW_Y_AUTO is not working as per information provided.
10. In overflow section OVERFLOW_Y_HIDDEN is not working as per information provided.
11. In overflow section OVERFLOW_Y_VISIBLE is not working as per information provided.
12. In overflow section OVERFLOW_Y_SCROLL is not working as per information provided.

**Comment by jyoti1610** [comment]
**Problem :** Overflow is not working as per the refarence.
**Attachment :**
![Screenshot 2024-01-13 112221](https://github.com/wrappid/guide-module/assets/88906858/c020a8ca-8594-45cc-8add-7bae0ad28eb9)

**Possible Solution :**
![Screenshot 2024-01-13 113339](https://github.com/wrappid/guide-module/assets/88906858/26688000-1862-4637-89b3-6214230f9ca1)

**Comment by jyoti1610** [comment]
**Problem :** Overflow is not working as per the refarence still now.

**Attachment :**
![image](https://github.com/wrappid/guide-module/assets/88906858/71f0507f-d668-4a21-aef2-b64b16808877)


**Possible Solution :** Mentioned in the previous comment.

**Comment by Animesh1432** [comment]
As of now closing this issue
