### ISSUE TITLE
Style Utilities : Cursor

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#35]
1. What is the difference between "CURSOR_EW_RESIZE" and "CURSOR_E_RESIZE"? Information Missing
2. What is the difference between "CURSOR_NE_RESIZE" and "CURSOR_NESW_RESIZE"? Information Missing
3. What is the difference between "CURSOR_NW_RESIZE" and "CURSOR_NWSE_RESIZE"? Information Missing

**Comment by Edithmark42** [comment]
- The alphabets stands for the **N**orth(Top), **E**ast(Right), **W**est(Left) and **S**outh(Bottom) direction.
- They provide the cursor that indicates if the content can be resized in the east, west or both directions.

![eresize](https://github.com/wrappid/guide-module/assets/58048663/80ac6171-e413-4e0a-bcbe-e54d84eab7ec)


- Depending on your operating system, desktop environment, and theme: These cursors may or may not be different from each other:

- - Windows 10:

![ewresize](https://github.com/wrappid/guide-module/assets/58048663/00de0a3b-dc61-46e7-8e6b-994b18a4eeac)

**Comment by Animesh1432** [comment]
1. What is the function of the auto cursor?
2. What is the function of the Initial cursor?
3. Can not understand the function of CURSOR_NWSE_RESIZE?

**Comment by Edithmark42** [comment]
please refer to te above mentioned comment

> * The alphabets stands for the **N**orth(Top), **E**ast(Right), **W**est(Left) and **S**outh(Bottom) direction.
> * They provide the cursor that indicates if the content can be resized in the east, west or both directions.
> 
> ![eresize](https://private-user-images.githubusercontent.com/58048663/296181115-80ac6171-e413-4e0a-bcbe-e54d84eab7ec.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwOTcsIm5iZiI6MTcwNjAxMjc5NywicGF0aCI6Ii81ODA0ODY2My8yOTYxODExMTUtODBhYzYxNzEtZTQxMy00ZTBhLWJjYmUtZTU0ZDg0ZWFiN2VjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmVhODE0NGIzYmEwYTJhZGI5ZjVkMWUyMzc1YzY4ODQ5MjE2NGMzMjIyOTAyNGFkYWNjMmJlNWQ3YTFlNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CwYTwbGYKMIYoavhUaO6D0ENQHzY-V2PWbJnJ4d92Zs) [ ![eresize](https://private-user-images.githubusercontent.com/58048663/296181115-80ac6171-e413-4e0a-bcbe-e54d84eab7ec.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwOTcsIm5iZiI6MTcwNjAxMjc5NywicGF0aCI6Ii81ODA0ODY2My8yOTYxODExMTUtODBhYzYxNzEtZTQxMy00ZTBhLWJjYmUtZTU0ZDg0ZWFiN2VjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmVhODE0NGIzYmEwYTJhZGI5ZjVkMWUyMzc1YzY4ODQ5MjE2NGMzMjIyOTAyNGFkYWNjMmJlNWQ3YTFlNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CwYTwbGYKMIYoavhUaO6D0ENQHzY-V2PWbJnJ4d92Zs) ](https://private-user-images.githubusercontent.com/58048663/296181115-80ac6171-e413-4e0a-bcbe-e54d84eab7ec.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwOTcsIm5iZiI6MTcwNjAxMjc5NywicGF0aCI6Ii81ODA0ODY2My8yOTYxODExMTUtODBhYzYxNzEtZTQxMy00ZTBhLWJjYmUtZTU0ZDg0ZWFiN2VjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmVhODE0NGIzYmEwYTJhZGI5ZjVkMWUyMzc1YzY4ODQ5MjE2NGMzMjIyOTAyNGFkYWNjMmJlNWQ3YTFlNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CwYTwbGYKMIYoavhUaO6D0ENQHzY-V2PWbJnJ4d92Zs) [ ](https://private-user-images.githubusercontent.com/58048663/296181115-80ac6171-e413-4e0a-bcbe-e54d84eab7ec.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwOTcsIm5iZiI6MTcwNjAxMjc5NywicGF0aCI6Ii81ODA0ODY2My8yOTYxODExMTUtODBhYzYxNzEtZTQxMy00ZTBhLWJjYmUtZTU0ZDg0ZWFiN2VjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmVhODE0NGIzYmEwYTJhZGI5ZjVkMWUyMzc1YzY4ODQ5MjE2NGMzMjIyOTAyNGFkYWNjMmJlNWQ3YTFlNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CwYTwbGYKMIYoavhUaO6D0ENQHzY-V2PWbJnJ4d92Zs)
> 
> * Depending on your operating system, desktop environment, and theme: These cursors may or may not be different from each other:
> * * Windows 10:
> 
> ![ewresize](https://private-user-images.githubusercontent.com/58048663/296181171-00de0a3b-dc61-46e7-8e6b-994b18a4eeac.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwOTcsIm5iZiI6MTcwNjAxMjc5NywicGF0aCI6Ii81ODA0ODY2My8yOTYxODExNzEtMDBkZTBhM2ItZGM2MS00NmU3LThlNmItOTk0YjE4YTRlZWFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTU2NTI1Yzk0OGQ4ODgxMTFlNWQ2NDE4ZTBkM2MyNjY5NTcyZjdhODUyNzdmNThlZDllMzEzMzFkZGMwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZQ5Lki3bM5ARaWyH4NLZsy7efFQ4zMINtsXH58ozZy8) [ ![ewresize](https://private-user-images.githubusercontent.com/58048663/296181171-00de0a3b-dc61-46e7-8e6b-994b18a4eeac.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwOTcsIm5iZiI6MTcwNjAxMjc5NywicGF0aCI6Ii81ODA0ODY2My8yOTYxODExNzEtMDBkZTBhM2ItZGM2MS00NmU3LThlNmItOTk0YjE4YTRlZWFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTU2NTI1Yzk0OGQ4ODgxMTFlNWQ2NDE4ZTBkM2MyNjY5NTcyZjdhODUyNzdmNThlZDllMzEzMzFkZGMwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZQ5Lki3bM5ARaWyH4NLZsy7efFQ4zMINtsXH58ozZy8) ](https://private-user-images.githubusercontent.com/58048663/296181171-00de0a3b-dc61-46e7-8e6b-994b18a4eeac.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwOTcsIm5iZiI6MTcwNjAxMjc5NywicGF0aCI6Ii81ODA0ODY2My8yOTYxODExNzEtMDBkZTBhM2ItZGM2MS00NmU3LThlNmItOTk0YjE4YTRlZWFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTU2NTI1Yzk0OGQ4ODgxMTFlNWQ2NDE4ZTBkM2MyNjY5NTcyZjdhODUyNzdmNThlZDllMzEzMzFkZGMwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZQ5Lki3bM5ARaWyH4NLZsy7efFQ4zMINtsXH58ozZy8) [ ](https://private-user-images.githubusercontent.com/58048663/296181171-00de0a3b-dc61-46e7-8e6b-994b18a4eeac.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwOTcsIm5iZiI6MTcwNjAxMjc5NywicGF0aCI6Ii81ODA0ODY2My8yOTYxODExNzEtMDBkZTBhM2ItZGM2MS00NmU3LThlNmItOTk0YjE4YTRlZWFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTU2NTI1Yzk0OGQ4ODgxMTFlNWQ2NDE4ZTBkM2MyNjY5NTcyZjdhODUyNzdmNThlZDllMzEzMzFkZGMwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZQ5Lki3bM5ARaWyH4NLZsy7efFQ4zMINtsXH58ozZy8)
