### ISSUE TITLE
Style Utilities : Display not valid

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#36]
1. In examples
   every example name is in the wrong place.
2. Need a more detailed description.
3. Need reference document for testing bootstrap doc is not sufficient for this particular section.

**Comment by Edithmark42** [comment]
1. The Names are shifted to bottom, and Box1, Box2 label added.
2. The description is self- explanatory.
3. please refer to display properties from bootstrap for better understanding.
