### ISSUE TITLE
Style Utilities : Opacity

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#41]
1. "The values are 0, 5, 10, ... , 100 with a step of 5." steps are not mentioned 
2. From opacity 80 to 100 all the boxes look all same.  Suggesting to follow reference document. It will be great if you use color filled boxes rather that this types of box.

**Comment by Animesh1432** [comment]
All the functions are working but there is some problem
1. change the font color of the content from blue to black or any suitable color.
![image](https://github.com/wrappid/guide-module/assets/105671990/38d64c08-508a-4da0-9418-b253b2ab7b4f)
2. The alignment of the text in the box should be center-align.
3. Why the color of the boxes are blue? Provide me theme document

**Comment by Edithmark42** [comment]
1. The font color is Black but it is getting the opacity from its parent so it seems blue.
3. The theme documentation is provided in the issue :[ DEV_BORDER](https://github.com/wrappid/guide-module/issues/25#issuecomment-1891345008).

**Comment by Animesh1432** [comment]
![image](https://github.com/wrappid/guide-module/assets/105671990/f79352a0-41ee-46b5-8511-c9643f8b3cc8)

OPACITY_100 should be in the box and center aligned.

**Comment by Edithmark42** [comment]
Why?

**Comment by Animesh1432** [comment]
because it will looks good

**Comment by Edithmark42** [comment]
Give me some suggestion.

**Comment by Animesh1432** [comment]
As of now closing this issue
