### ISSUE TITLE
Style utilities : Visibility

### ISSUE THREAD

**Issue by jyoti1610** [wrappid/guide-module#44]
**Problem :**
- - Example of visibility and  invisibility not clearly deferentiate by the user.

**Possible Solution :**
- - Fill the content box by any color.

**Comment by Animesh1432** [comment]
Primary Test Pass.

**Problem:**  

1. It is working but It will be used as a "Guide". So in this case the guide should look good as reference document.

- Change Font style
- Make the heading bold
- 
![image](https://github.com/wrappid/guide-module/assets/105671990/a9e86299-bb20-4634-a787-ee4d9546ff2f)
 Use these type of content. Highlight the keywords.

- Add Codes by which user can use it.
@Edithmark42

**Comment by jyoti1610** [comment]
Current status of the issue: Passed ( As of now ).
App Info :

|  Key  |  Value  |
| ---- | ---- |
| Fronend URL | http://wrappid.framework.s3-website.ap-south-1.amazonaws.com/guide/styles |
| Fronend Version | 0.0.1 |


Desktop :

|  Key  |  Value  |
| ---- | ---- |
| OS | Windows 11 |
| Browser | Google Chrome |
| Version | Version 120.0.6099.217 (Official Build) (64-bit) |

**Comment by techoneel** [comment]
issue re-opened with no comments.
assigning @Animesh1432 again
