### ISSUE TITLE
bug: Component ui

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#54]
- [ ] The proper navigation bar missing as like reference document
 

from #55 

- [ ] ![image](https://github.com/wrappid/guide-module/assets/105671990/f3f30fb1-4ea1-4654-a42f-fb4f2e62c620)

Fix The heading

from #56 

- [ ] ![image](https://github.com/wrappid/guide-module/assets/105671990/b1be10ca-c3a8-40d1-977b-3de04e6d2129)
 Alignment should be fix 

from #57 

- [ ] Wrappid 
![image](https://github.com/wrappid/guide-module/assets/105671990/018d7602-7bf2-4cb8-9cf1-c5c64f86ec6e)
 MUI
![image](https://github.com/wrappid/guide-module/assets/105671990/13e7b678-7fb9-4a98-b0e7-84259d165336)

MUI looking good fix this in wrappid

from #62 

- [ ] Wrappid Theme
![image](https://github.com/wrappid/guide-module/assets/105671990/d2495324-6416-4304-994b-32ab5dd246f0)

MUI theme
![image](https://github.com/wrappid/guide-module/assets/105671990/47c8da83-26f1-4a7c-b30f-e8ca64d0e05d)
 
Compare these two pictures which is looking more nice.  Choose a appropriate color theme for the guide module

from #65 

- [ ] main body scrolling bar missing 

from #74 

- [ ] **Problem :**
1. As I have tested style page before this , there all the headings are in uppercase therefore you should follow the same pattern.
as example ( "Core badge" to "CORE BADGE" ).
2.
![image](https://github.com/wrappid/guide-module/assets/88906858/ae5e8689-89f2-4ef5-92d1-2e07acc57d85)
This huge blank space looks odd to the user.

 from #75 

- [ ] **Problem :**
1. Headings should be in uppercase.
2. 
![image](https://github.com/wrappid/guide-module/assets/88906858/9f5c1780-708e-47fc-a180-558ab792e57c)
Gap is needed between those chips.
3.
![image](https://github.com/wrappid/guide-module/assets/88906858/34a82eb0-a9a2-44c8-ad15-afa4b36c1376)
Code is overlalping , fix this.
4.
![image](https://github.com/wrappid/guide-module/assets/88906858/9685e446-7274-4e49-ae87-0907ab1c7445)
No need of this blank space.

from #70 
Need Reference document for Valid Props, alt
OPTIONAL, src, variant, component, imgProps, sizes, srcSet, styleClasses, key, ref, children,

**Comment by irkfaisal** [comment]
closing this issue, we have changed the this UI
