### ISSUE TITLE
Create styleUtility Samples

### ISSUE THREAD

**Issue by Edithmark42** [wrappid/guide-module#6]
**For Testing**
- Need to check if all the utility components in the page "[/guide/styles](http://wrappid.framework.s3-website.ap-south-1.amazonaws.com/guide/styles)" are working. Except some Utilities with warning message which are not working at the moment.
- Need to check if all the utilities marked as working are working as intended. And the Table of content is showing all the utility names.

- - Utilities that are working
> - DEV_BORDER
> - BG
> - BORDER
> - COLOR
> - CURSOR
> - DISPLAY
> - FLEX
> - HEIGHT
> - INTERACTIONS
> - MARGIN
> - OPACITY
> - OVERFLOW
> - PADDING
> - SHADOW
> - TEXT
> - VISIBILITY
> - WIDTH

- - Utilities that are not working 

> - ALIGNMENT
> - FLOAT
> - GAP
> - OBJECT_FIT
> - PADDING
> - POSITION
> - VERTICAL_ALIGN
> - Z_INDEX

- For understanding how the utilities are intended to work. Please refer to the [Bootstrap 5](https://getbootstrap.com/docs/5.0/layout/utilities/) documentation.

**Comment by Edithmark42** [comment]
**Utilities that are working**

> - DEV_BORDER
> - BG
> - BORDER
> - COLOR
> - CURSOR
> - DISPLAY
> - FLEX
> - HEIGHT
> - INTERACTIONS
> - MARGIN
> - OPACITY
> - OVERFLOW
> - PADDING
> - SHADOW
> - TEXT
> - VISIBILITY
> - WIDTH

**Utilities thar are not working**

> - ALIGNMENT
> - FLOAT
> - GAP
> - OBJECT_FIT
> - PADDING
> - POSITION
> - VERTICAL_ALIGN
> - Z_INDEX

**Comment by Animesh1432** [comment]
There is no description of what I have to test so please give me all the details.

**Comment by Animesh1432** [comment]
Provide me URLs where to perform the testings @wrappid/devops-team ?

**Comment by anantakumarghosh** [comment]
> Provide me URLs where to perform the testings @wrappid/devops-team ?

Please refer wrappid/workflow-mgmt#25

**Comment by Animesh1432** [comment]
Cannot understand the second paragraph of point number 2 in the description. So Please share more specific details @Edithmark42. 
And for point 3 in MUI which part do I have to check?

**Comment by Animesh1432** [comment]
I cannot understand which current version i am testing @wrappid/devops-team

**Comment by Animesh1432** [comment]
How can I know all the things are showing properly as we want to see? Is there any specific reference by which I can compare your work and test the whole thing ? @Edithmark42

**Comment by Edithmark42** [comment]
> How can I know all the things are showing properly as we want to see? Is there any specific reference by which I can compare your work and test the whole thing ? @Edithmark42

You may visit bootstrap style utilities documentation for the reference.

**Comment by Animesh1432** [comment]
> **For Testing**
> 
> * Need to check if all the utility components in the page "[/guide/styles](http://wrappid.framework.s3-website.ap-south-1.amazonaws.com/guide/styles)" are working. Except some Utilities with warning message which are not working at the moment.
> * Need to check if all the utilities marked as working are working as intended. And the Table of content is showing all the utility names.
> * * Utilities that are working
> 
> > * DEV_BORDER
> > * BG
> > * BORDER
> > * COLOR
> > * CURSOR
> > * DISPLAY
> > * FLEX
> > * HEIGHT
> > * INTERACTIONS
> > * MARGIN
> > * OPACITY
> > * OVERFLOW
> > * PADDING
> > * SHADOW
> > * TEXT
> > * VISIBILITY
> > * WIDTH
> 
> * * Utilities that are not working
> 
> > * ALIGNMENT
> > * FLOAT
> > * GAP
> > * OBJECT_FIT
> > * PADDING
> > * POSITION
> > * VERTICAL_ALIGN
> > * Z_INDEX
> 
> * For understanding how the utilities are intended to work. Please refer to the [Bootstrap 5](https://getbootstrap.com/docs/5.0/layout/utilities/) documentation.

Ok Now I can Understand how the utilities are working but as you have a clear idea of where what should be shown and you make it that way how can I know your idol thought is there any sample you are following?

**Comment by jyoti1610** [comment]
You ( @Edithmark42 ) gave the list ,which are not working , those are as follows :  

- ALIGNMENT
- FLOAT
- GAP
- OBJECT_FIT
- PADDING
- POSITION
- VERTICAL_ALIGN
- Z_INDEX

I saw many section like "DATA DISPLAY" , "DATA TABLE" , "ICON" , "CORE FOOTER" , "LAYOUT"  etc. except which you have mentioned before. Can I check for those section ?
If not , please give the section names properly.

**Comment by Animesh1432** [comment]
As of now closing this issue
