### ISSUE TITLE
enhancement: Components Guide for Wrappid Developers

### ISSUE THREAD

**Issue by saifalamkhan373** [wrappid/guide-module#7]
Developers guide document on how to use Core components

### What problem we're solving?
We need to structure the core components in a way that Wrappid developers can find everything one single page for further use in our product.

### What is the proposed solution?
In Core component every feature has a role to play in designing the UI of web and mobile. So each of these component has its own description. So we need to implement it in a way when we click in some core feature it should show every details of it to the  developers.

### Tasks in this issue

- [ ] Prepare usage document for all components.
- [x] wrappid/core#65

**Comment by irkfaisal** [comment]
working on the guide component

**Comment by samhere17** [comment]
There was an old issue for this task, https://github.com/wrappid/guide-module/issues/8
I am closing the same. Commenting to keep ref.

**Comment by irkfaisal** [comment]
This issue was related to create documentation for wrappid components documentation. We have separate issues for every components.
