### ISSUE TITLE
bug: avatar group

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/guide-module#72]
- [ ] ![image](https://github.com/wrappid/guide-module/assets/105671990/85ca12fb-e115-4314-b662-e90a37182fa2)

As I can see in the grouped description there should be "coreAvatargroup" and max and core avatar group should be highlighted like reference document

![image](https://github.com/wrappid/guide-module/assets/105671990/e3af4439-781e-49ee-b7aa-3199dd638811)

From #73 

- [ ] Can not understand Valid stand is a different section 

![image](https://github.com/wrappid/guide-module/assets/105671990/2a544bdf-e109-4203-a466-dc18d870d01d)
 Solution : use different font color

from #77 

- [ ] Use uppercase in heading 

![image](https://github.com/wrappid/guide-module/assets/105671990/1930ee63-a49e-439f-bc11-e538841b365a)
 from #78 

- [ ] Description not understandable.

make it like reference document
![image](https://github.com/wrappid/guide-module/assets/105671990/ad125f38-6bf2-4947-b043-a50617b82bd1)
![image](https://github.com/wrappid/guide-module/assets/105671990/212b364b-99b9-420f-9d5a-dd74b36d6360)
 from #79 

- [ ] I reference document in the type I found this 

![image](https://github.com/wrappid/guide-module/assets/105671990/d05849e8-87dd-4966-bc63-dc507063e496)
 but in your doc 

![image](https://github.com/wrappid/guide-module/assets/105671990/e1170bf8-4d8b-43e1-8678-adef6d26a817)
 please look into this 

- [ ] From https://github.com/wrappid/guide-module/issues/80

There is  blank space after invalid props fix this 
![image](https://github.com/wrappid/guide-module/assets/105671990/cc9fe49f-62b5-4d5c-a3b0-6738b29da610)

**Comment by Animesh1432** [comment]
#64

**Comment by irkfaisal** [comment]
invalid issue. This guide page has been changed a little so some of design is different from the current image above.
