### ISSUE TITLE
Components : Core badge

### ISSUE THREAD

**Issue by jyoti1610** [wrappid/guide-module#74]
**Problem :**
1. As I have tested style page before this , there all the headings are in uppercase therefore you should follow the same pattern.
as example ( "Core badge" to "CORE BADGE" ).
2.
![image](https://github.com/wrappid/guide-module/assets/88906858/ae5e8689-89f2-4ef5-92d1-2e07acc57d85)
This huge blank space looks odd to the user.

**Comment by Animesh1432** [comment]
Description Copied to #54
