### ISSUE TITLE
Components : Core Chip

### ISSUE THREAD

**Issue by jyoti1610** [wrappid/guide-module#75]
**Problem :**
1. Headings should be in uppercase.
2. 
![image](https://github.com/wrappid/guide-module/assets/88906858/9f5c1780-708e-47fc-a180-558ab792e57c)
Gap is needed between those chips.
3.
![image](https://github.com/wrappid/guide-module/assets/88906858/34a82eb0-a9a2-44c8-ad15-afa4b36c1376)
Code is overlalping , fix this.
4.
![image](https://github.com/wrappid/guide-module/assets/88906858/9685e446-7274-4e49-ae87-0907ab1c7445)
No need of this blank space.

**Comment by Animesh1432** [comment]
Description Copied to #54
