### ISSUE TITLE
enhancement: Component Documentation UI re structuring

### ISSUE THREAD

**Issue by saifalamkhan373** [wrappid/guide-module#9]
This UI re-structuring have two prior task(s)

1. Update documentation schema based on UI requirements.
2. UI re-structuring based on MUI component page design  [eg. https://mui.com/material-ui/react-button/]

**Comment by irkfaisal** [comment]
Working on the components documentation.

**Comment by samhere17** [comment]
Will be handled in https://github.com/wrappid/guide-module/issues/7
